import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { ApolloWrapper } from "./lib/ApolloWrapper";
const inter = Inter({ subsets: ["latin"] });
import OrdersState from "./context/orders/OrdersState";


export const metadata = {
  title: "My CRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className} >
          <main className="flex">
            <ApolloWrapper>
              <OrdersState>
                <Sidebar />
                <div className="p-5 bg-gray-200 sm:w-2/3 xl:w-4/5">
                  {children}
                </div>
              </OrdersState>
            </ApolloWrapper>
          </main>
        </body>
      </html>
  );
}
