import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My CRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <Sidebar />
          <div className="p-5 bg-gray-200 sm:w-2/3 xl:w-4/5">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
